
name: 'Run Orosu Client'
description: 'Install and run orosu-client with specified parameters'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  address:
    description: 'Orosu server address'
    required: true
  key:
    description: 'Authentication key'
    required: true
  script:
    description: 'Script to execute'
    required: true
  file:
    description: 'Attached file to upload (newline delimited)'
    required: false
  chunk_size:
    description: 'Chunk size in bytes for file uploads (default: 65536)'
    required: false
    default: '65536'
  arguments:
    description: 'Script arguments (space-separated string, e.g. "arg1 arg2 arg3")'
    required: false
    default: ''
  log_level:
    description: 'Log level (default: info)'
    required: false
    default: 'info'

runs:
  using: 'composite'
  steps:
    - name: Get version from Cargo.toml
      id: version
      shell: bash
      run: |
        VERSION=$(grep '^version' $GITHUB_ACTION_PATH/Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Install orosu-client
      shell: bash
      run: |
        INSTALLED_VERSION=$(dpkg-query -W -f='${Version}' orosu-client 2>/dev/null || echo "")
        REQUIRED_VERSION="${{ steps.version.outputs.version }}-1"
        if [ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]; then
          sudo apt-get update
          sudo apt-get install -y curl gnupg ca-certificates
          if [ -z "$INSTALLED_VERSION" ]; then
            curl -fsSL https://packages.nerdy.pro/NerdyPro.gpg | sudo gpg --dearmor -o /usr/share/keyrings/nerdy-pro.gpg
            echo "deb [signed-by=/usr/share/keyrings/nerdy-pro.gpg] https://packages.nerdy.pro/ stable main" | sudo tee /etc/apt/sources.list.d/nerdy-pro.list
            sudo apt update
          fi
          sudo apt install -y orosu-client=$REQUIRED_VERSION
        else
          echo "orosu-client $REQUIRED_VERSION already installed"
        fi

    - name: Run orosu-client
      shell: bash
      run: |
        orosu-client \
          --address "${{ inputs.address }}" \
          --script "${{ inputs.script }}" \
          --key "${{ inputs.key }}" \
          --chunk-size "${{ inputs.chunk_size }}" \
          --log-level "${{ inputs.log_level }}" \
          ${{ inputs.file && '--file ' || ''}}${{ inputs.file }} \
          ${{ inputs.arguments }}