
name: 'Run Orosu Client'
description: 'Execute remote scripts on Orosu server with file upload capabilities'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  address:
    description: 'Orosu server address. Must be a valid websocket URL, e.g. wss://host:port/path or ws://host:port/path'
    required: true
  key:
    description: 'Authentication key. Can be generated on the server using orosu-keygen. Private key is required.'
    required: true
  script:
    description: 'Script to execute. Should be configured on the server.'
    required: true
  file:
    description: 'Attached file to upload (newline delimited). The file will be accessible in the script as ATTACHMENTS_DIR environment variable.'
    required: false
  chunk_size:
    description: 'Chunk size in bytes for file uploads (default: 65536).'
    required: false
    default: '65536'
  arguments:
    description: 'Script arguments (space-separated string, e.g. "arg1 arg2 arg3"). These arguments will be passed to the script as $1, $2, etc.'
    required: false
    default: ''
  log_level:
    description: 'Log level (default: info)'
    required: false
    default: 'info'

runs:
  using: 'composite'
  steps:
    - name: Get version from Cargo.toml
      id: version
      shell: bash
      run: |
        VERSION=$(grep '^version' $GITHUB_ACTION_PATH/Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Install orosu-client
      shell: bash
      run: |
        INSTALLED_VERSION=$(dpkg-query -W -f='${Version}' orosu-client 2>/dev/null || echo "")
        REQUIRED_VERSION="${{ steps.version.outputs.version }}-1"
        if [ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]; then
          sudo apt-get update
          sudo apt-get install -y curl gnupg ca-certificates
          if [ -z "$INSTALLED_VERSION" ]; then
            curl -fsSL https://packages.nerdy.pro/NerdyPro.gpg | sudo gpg --dearmor -o /usr/share/keyrings/nerdy-pro.gpg
            echo "deb [signed-by=/usr/share/keyrings/nerdy-pro.gpg] https://packages.nerdy.pro/ stable main" | sudo tee /etc/apt/sources.list.d/nerdy-pro.list
            sudo apt update
          fi
          sudo apt install -y orosu-client=$REQUIRED_VERSION
        else
          echo "orosu-client $REQUIRED_VERSION already installed"
        fi

    - name: Run orosu-client
      shell: bash
      run: |
        FILE_ARGS=""
          if [ -n "${{ inputs.file }}" ]; then
            while IFS= read -r pattern; do
              [ -z "$pattern" ] && continue
              for file in $pattern; do
                if [ -f "$file" ]; then
                  FILE_ARGS="$FILE_ARGS --file $file"
                fi
            done
          done <<< "${{ inputs.file }}"
        fi
        
        orosu-client \
          --address "${{ inputs.address }}" \
          --script "${{ inputs.script }}" \
          --key "${{ inputs.key }}" \
          --chunk-size "${{ inputs.chunk_size }}" \
          --log-level "${{ inputs.log_level }}" \
          $FILE_ARGS \
          ${{ inputs.arguments }}